# 文件路径：/opt/hotShop/docker-compose.yml
version: '3.8'

services:
  # 数据库服务
  mysql:
    image: mysql:8.0
    container_name: hotShop-mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: hotShop
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "4306:3306"
    networks:
      - hotShop-network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 5s
      timeout: 3s
      retries: 5

  # Redis服务
  redis:
    image: redis:alpine
    container_name: hotShop-redis
    ports:
      - "7379:6379"
    volumes:
      - redis_data:/data
    networks:
      - hotShop-network
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 5

  # RabbitMQ服务
  rabbitmq:
    image: rabbitmq:3.12-management-alpine
    container_name: hotShop-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin123
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - hotShop-network
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "status" ]
      interval: 10s
      timeout: 5s
      retries: 5


  admin-service:
    build:
      context: .
      args:
        MODULE: admin
        PROFILE: ""
    container_name: hotShop-admin
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/hotShop
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 123456
      SPRING_REDIS_HOST: redis
      SERVER_PORT: 8088
    ports:
      - "8088:8088"
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - hotShop-network

  portal-service:
    build:
      context: .
      args:
        MODULE: portal
        PROFILE: ""
    container_name: hotShop-portal
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://hotShop-mysql:3306/hotShop
      SPRING_REDIS_HOST: redis
      SPRING_RABBITMQ_HOST: rabbitmq
      SERVER_PORT: 8080
    ports:
       - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - hotShop-network

  task-service:
    build:
      context: .
      args:
        MODULE: task
        PROFILE: ""
    container_name: hotShop-task
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://hotShop-mysql:3306/hotShop
      SPRING_REDIS_HOST: redis
      SPRING_RABBITMQ_HOST: rabbitmq
      SERVER_PORT: 8888
    ports:
      - "8888:8888"
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - hotShop-network

volumes:
  mysql_data:
  redis_data:
  rabbitmq_data:

networks:
  hotShop-network:
    driver: bridge