# 文件路径：/opt/hotShop/docker-compose.yml
version: '3.8'

services:
  # 数据库服务（共用）
  mysql:
    image: mysql:8.0
    container_name: hotShop-mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: hotShop
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "4306:3306"
    networks:
      - hotShop-network

  # Redis服务（共用）
  redis:
    image: redis:alpine
    container_name: hotShop-redis
    ports:
      - "7379:6379"
    volumes:
      - redis_data:/data
    networks:
      - hotShop-network

  admin-service:
    build:
      context: .
      args:
        MODULE: admin
        PROFILE: prod
    environment:
      SERVICE_TYPE: admin # 指定运行 admin 服务
      SPRING_DATASOURCE_URL: jdbc:mysql://hotShop-mysql:3306/hot_shop
      SPRING_REDIS_HOST: hotShop-redis
    depends_on:
      - mysql
      - redis
    ports:
      - "8088:8088"
    networks:
      - hotShop-network

  portal-service:
    build:
      context: .
      args:
        MODULE: portal
        PROFILE: prod
    environment:
      SERVICE_TYPE: portal # 指定运行 portal 服务
      SPRING_DATASOURCE_URL: jdbc:mysql://hotShop-mysql:3306/hot_shop
      SPRING_REDIS_HOST: hotShop-redis
    depends_on:
      - mysql
      - redis
    ports:
      - "8080:8080"
    networks:
      - hotShop-network

volumes:
  mysql_data:
  redis_data:

networks:
  hotShop-network:
    driver: bridge