package com.real.common.audit;

public enum AuditResourceType {
    PURCHASE_DRAFT,
    PURCHASE_CONFIRMATION,
    AGENT_TOOL,
    AGENT_CONFIGURATION_DRAFT,
    FLASH_SALE_RESERVATION,
    AUTHENTICATION_SESSION,
    REFRESH_TOKEN_FAMILY,
    USER,
    CATALOG_PRODUCT,
    FLASH_SALE_ACTIVITY,
    OUTBOX_EVENT,
    SALES_ORDER,
    SALE_RESERVATION,
    PAYMENT_ORDER,
    PAYMENT_CALLBACK
}
