package com.real.common.audit;

public enum AuditAction {
    AGENT_TOOL_INVOKED,
    PURCHASE_CONFIRMATION_ISSUED,
    PURCHASE_CONFIRMATION_CONSUMED,
    PURCHASE_CONFIRMATION_REVOKED,
    PURCHASE_CONFIRMATION_ISSUE_DENIED,
    PURCHASE_CONFIRMATION_CONSUME_DENIED,
    PURCHASE_CONFIRMATION_REVOKE_DENIED,
    RESERVATION_COMPENSATED,
    AUTHENTICATION_LOGIN,
    REFRESH_TOKEN_REUSE_DETECTED,
    AGENT_DELEGATION_ISSUED,
    CATALOG_PRODUCT_CREATED,
    CATALOG_PRODUCT_UPDATED,
    CATALOG_STOCK_ADJUSTED,
    CATALOG_PRODUCT_DELETED,
    FLASH_SALE_ACTIVITY_LOADED,
    OUTBOX_REPLAY,
    INVENTORY_COMPENSATED,
    MOCK_PAYMENT_CALLBACK_ACCEPTED,
    MOCK_PAYMENT_CALLBACK_REJECTED
}
