package com.real.common.audit;

public enum AuditAction {
    AUTHENTICATION_LOGIN,
    REFRESH_TOKEN_REUSE_DETECTED,
    AGENT_DELEGATION_ISSUED,
    CATALOG_PRODUCT_CREATED,
    CATALOG_PRODUCT_UPDATED,
    CATALOG_PRODUCT_DELETED,
    FLASH_SALE_ACTIVITY_LOADED,
    OUTBOX_REPLAY,
    INVENTORY_COMPENSATED,
    MOCK_PAYMENT_CALLBACK_ACCEPTED,
    MOCK_PAYMENT_CALLBACK_REJECTED
}
