spring:
  application:
    name: portal
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:}
  config:
    import:
      - classpath:config/common-db.yml
      - classpath:config/common-redis.yml
      - classpath:config/common-jwt.yml
      - classpath:config/orderTimeoutConfig.yml

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/hotShop?useSSL=false&serverTimezone=UTC}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:123456}

  data:
    redis:
      host: ${SPRING_REDIS_HOST:localhost}
      port: ${SPRING_REDIS_PORT:6379}

  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:localhost}
    port: ${SPRING_RABBITMQ_PORT:5672}
    username: ${SPRING_RABBITMQ_USERNAME:guest}
    password: ${SPRING_RABBITMQ_PASSWORD:guest}
    publisher-confirm-type: correlated
    listener:
      simple:
        retry:
          enabled: true   # 开启消费重试
          max-attempts: 3 # 最大重试次数

rabbitmq:
  enabled: true

server:
  port: 8080

springdoc:
  swagger-ui:
    enabled: true
  api-docs:
    enabled: true

logging:
  level:
    org.springframework.security: DEBUG
    com.real: TRACE
