spring:
  application:
    name: admin
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:}
  config:
    import:
      - classpath:config/common-db.yml
      - classpath:config/common-redis.yml
      - classpath:config/common-jwt.yml

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/hotShop?useSSL=false&serverTimezone=UTC}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:123456}

  data:
    redis:
      host: ${SPRING_REDIS_HOST:localhost}
      port: ${SPRING_REDIS_PORT:6379}
      database: 0

  redis:
    database-1:
      host: ${SPRING_REDIS_HOST:localhost}
      port: ${SPRING_REDIS_PORT:6379}
      database: 1
      lettuce:
        pool:
          max-active: 8
          max-wait: -1
          max-idle: 8
          min-idle: 0

server:
  port: 8088

logging:
  level:
    org.springframework.security: DEBUG
    com.real: TRACE