spring:
  application:
    name: task
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:}
  config:
    import:
      - classpath:config/common-db.yml
      - classpath:config/common-redis.yml
      - classpath:config/common-jwt.yml

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/hotShop?useSSL=false&serverTimezone=UTC}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:123456}

  data:
    redis:
      host: ${SPRING_REDIS_HOST:localhost}
      port: ${SPRING_REDIS_PORT:6379}


server:
  port: 8888

logging:
  level:
    com.real: TRACE

timeout:
  orderCancel: 30