spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      data-source-properties:
        rewriteBatchedStatements: true

mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.real.domain.entity
  configuration:
    mapUnderscoreToCamelCase: true